name: its_test1
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - seaborn
  - matplotlib
  - xgboost
  - flask
  - flask-cors
  - sqlalchemy
  - requests
  - openpyxl